In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


In [3]:
ar = np.array([6,7,8,9,10,"prime"])
mat = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(arr)
print(mat)

[1 2 3 4 5]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [4]:
# create with zeroes
arr1 = np.zeros((3,3),"int64") # int64 for integers 
print(arr1)

arr2 = np.ones((3,3),"int64") # int64 for integers 
print(arr2)

arr3 = np.full((3,3),"100") # int64 for integers 
print(arr3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[['100' '100' '100']
 ['100' '100' '100']
 ['100' '100' '100']]


# properties 

In [5]:
arr = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(arr)
print(arr.size )
print(arr.shape)
print(arr.ndim)
print(arr.dtype)





[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
9
(3, 3)
2
int64


# operations on arrays

## 1.reshaping 

In [6]:
t_arr = np.array([[1,2,3],[4,5,6]])
print(t_arr,t_arr.shape)
reshape = t_arr.reshape((3,2))
print(reshape,reshape.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [7]:
reshape2 = t_arr.flatten() # to convert to 1D array u need to flatten 
print(reshape2,reshape2.shape)

[1 2 3 4 5 6] (6,)


## indexing 

In [8]:
arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [ ]:
print(arr[arr>2]) ## boolean indexing 

[3 4 5]


In [ ]:
print(arr[arr%2 ==1 ]) #boolean indexing 

[1 3 5]


## slicing 

In [14]:
arr = np.array([1,4,6,8,7,2])
print(arr[1:5])
print(arr[:6]) 
print(arr[3:]) 
print(arr[::2])

[4 6 8 7]
[1 4 6 8 7 2]
[8 7 2]
[1 6 7]
