In [1]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3,4,5])
print(arr1,type(arr1),arr1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


In [14]:
arr2 = np.array([6,7,8,9,10,"prime"])
mat = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(arr2)
print(mat)

['6' '7' '8' '9' '10' 'prime']
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
